production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    solr_home: /deployment/production/videoresume/shared/solr
    data_path: /deployment/production/videoresume/shared/solr/data/production
    pid_dir: /deployment/production/videoresume/shared/pids/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
    